# Generated by Django 4.1.2 on 2022-12-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_currentprice_product_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestedPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
